version: '3.8'

services:
  kong:
    image: ghcr.io/jiramot/kong-oauth2-plugin:0.1.0
    ports:
      - "8000:8000"
    volumes:
      - ./kong/config/config.yml:/tmp/config.yml
    environment:
      - KONG_DATABASE=off
      - KONG_DECLARATIVE_CONFIG=/tmp/config.yml
      - KONG_PLUGINS=bundled,open-api
      - KONG_PLUGINSERVER_NAMES=open-api
      - KONG_PLUGINSERVER_OPEN_API_START_CMD=/usr/local/bin/open-api
      - KONG_PLUGINSERVER_OPEN_API_QUERY_CMD=/usr/local/bin/open-api -dump
      - KONG_PROXY_LISTEN=0.0.0.0:8000
      - KONG_LOG_LEVEL=debug

  profile:
    image: ghcr.io/jiramot/go-profile-resource:0.1.2

  redis:
    image: redis

#  partner:
#    image: ghcr.io/jiramot/kong-oauth2-plugin:latest
#    ports:
#      - "9100:80"
    
  ssoweb:
    image: ghcr.io/jiramot/express-oauth2-sso-web:0.1.1
    ports:
      - "3000:3000"
    environment:
      - OAUTH_ADMIN_ENDPOINT=http://oauth2-admin:8081

  oauth2-admin:
    image: ghcr.io/jiramot/go-oauth2:0.1.4
    command:
      - ./admin
    volumes:
      - ./oauth/config.yaml:/app/config.yaml
    environment:
      - REDIS_HOST=redis
      - REDIS_PORT=6379

  oauth2-public:
    image: ghcr.io/jiramot/go-oauth2:0.1.4
    command:
      - ./admin
    ports:
      - "8080:8080"
    volumes:
      - ./oauth/config.yaml:/app/config.yaml
    environment:
      - REDIS_HOST=redis
      - REDIS_PORT=6379

