apiVersion: v1
kind: ConfigMap
metadata:
  name: kong-config
data:
  config.yaml: |
    _format_version: '2.1'
    services:
      - name: auth
        url: http://{{ .Release.Name }}-openapi-oauth2-public/oauth2/auth
        routes:
          - paths:
              - '/oauth2/auth'
      - name: token
        url: http://{{ .Release.Name }}-openapi-oauth2-public/oauth2/token
        routes:
          - paths:
              - '/oauth2/token'
      - name: profile
        url: http://{{ .Release.Name }}-openapi-profile-resource
        routes:
          - paths:
              - '/profile'
        plugins:
          - name: open-api
            config:
              endpoint: "http://{{ .Release.Name }}-openapi-oauth2-admin/oauth2/introspect"