apiVersion: v1
kind: ConfigMap
metadata:
  name: kong-config
data:
  config.yaml: |
    _format_version: '2.1'
    services:
      - name: profile
        url: http://openapi-openapi-profile-resource
        routes:
          - paths:
              - '/profile'
        plugins:
          - name: open-api
            config:
              endpoint: "http://openapi-openapi-oauth2-admin/oauth2/introspect"