_format_version: '2.1'
services:
  - name: profile
    url: http://profile:10000
    routes:
      - paths:
          - '/profile'
    plugins:
      - name: open-api
        config:
          endpoint: "http://oauth2-admin:8081/oauth2/introspect"