_format_version: '2.1'
services:
  - name: auth
    url: http://oauth2-public:8080/oauth2/auth
    routes:
      - paths:
          - '/oauth2/auth'
  - name: token
    url: http://oauth2-public:8080/oauth2/token
    routes:
      - paths:
          - '/oauth2/token'
  - name: profile
    url: http://profile:10000
    routes:
      - paths:
          - '/profile'
    plugins:
      - name: open-api
        config:
          endpoint: "http://oauth2-admin:8081/oauth2/introspect"
      - name: cors
        service: profile
        config:
          origins:
            - "*"
          methods:
            - GET
          credentials: true
          max_age: 3600
          preflight_continue: false