apiVersion: v2
name: openapi-oauth2-public
description: A Helm chart for Kubernetes

type: application

version: 0.1.2

appVersion: "1.16.0"

dependencies:
  - name: kong
    repository: "https://charts.konghq.com"
    condition: kong.enabled
    version: 2.3.0
    alias: kong
