apiVersion: v1
kind: Service
metadata:
  name: {{ include "openapi-profile-resource.fullname" . }}
  labels:
    {{- include "openapi-profile-resource.labels" . | nindent 4 }}
spec:
  type: {{ .Values.service.type }}
  ports:
    - port: {{ .Values.service.port }}
      targetPort: 10000
      protocol: TCP
  selector:
    {{- include "openapi-profile-resource.selectorLabels" . | nindent 4 }}
