apiVersion: cert-manager.io/v1
kind: Certificate
metadata:
  name: cert-access-authz-one
  namespace: openapi
spec:
  secretName: access-autz-one-certificate
  issuerRef:
    name: authz-one-issuer
    kind: ClusterIssuer
  dnsNames:
    - access.authz.one
---
apiVersion: cert-manager.io/v1
kind: Certificate
metadata:
  name: cert-sso-authz-one
  namespace: openapi
spec:
  secretName: sso-autz-one-certificate
  issuerRef:
    name: authz-one-issuer
    kind: ClusterIssuer
  dnsNames:
    - sso.authz.one