apiVersion: v1
kind: ConfigMap
metadata:
  name: openapi-oauth2-config
data:
  config.yaml: |
    client:
      - client_id: 1234
        client_secret: 12345
        scope: "openid profile"
        redirect_url: "http://localhost:9100"
      - client_id: 6789
        client_secret: 12345
        scope: "openid"
        redirect_url: "http://localhost:9100"
    login_endpoint: http://localhost:3000/login