apiVersion: v1
kind: Service
metadata:
  name: {{ include "openapi-oauth2-public.fullname" . }}
  labels:
    {{- include "openapi-oauth2-public.labels" . | nindent 4 }}
spec:
  type: {{ .Values.service.type }}
  ports:
    - port: {{ .Values.service.port }}
      targetPort: 8081
      protocol: TCP
  selector:
    {{- include "openapi-oauth2-public.selectorLabels" . | nindent 4 }}
