apiVersion: v1
kind: Service
metadata:
  name: {{ include "app-gallery.fullname" . }}
  labels:
    {{- include "app-gallery.labels" . | nindent 4 }}
spec:
  type: {{ .Values.service.type }}
  ports:
    - port: {{ .Values.service.port }}
      targetPort: 8082
      protocol: TCP
  selector:
    {{- include "app-gallery.selectorLabels" . | nindent 4 }}
