client:
  - client_id: 1234
    client_secret: 12345
    scope: "openid profile"
    redirect_url: "http://localhost:9100"
  - client_id: 6789
    client_secret: 12345
    scope: "openid"
    redirect_url: "http://localhost:9100"

login_endpoint: http://localhost:3000/login

access_token_duration: 1h
access_log_enabled: false