@startuml
hide footbox
participant "Partner API" as partner
participant "Authorization Server" as oauth
participant "Your API" as openapi

autonumber
partner -> oauth: Authenticate with Client ID + Client Secret \nto /token
oauth -> oauth: Validate \nClient ID + Client Secret
oauth -> partner: Access Token

partner -> openapi: Request data with Access Token
openapi -> partner: Response

@enduml