apiVersion: v2
appVersion: "1.0"
description: A Helm chart for Kubernetes for openapi
name: openapi
version: 0.1.2

dependencies:
  - name: kong
    repository: "https://charts.konghq.com"
    condition: kong.enabled
    version: 2.3.0
    alias: kong

  - name: redis
    repository: "https://charts.bitnami.com/bitnami"
    condition: redis.enabled
    version: 15.3.2
    alias: redis
