apiVersion: v2
appVersion: "0.1.4"
description: A Helm chart for Kubernetes for openapi
home: https://github.com/jiramot/simple-openapi
sources:
  - https://github.com/jiramot/simple-openapi
maintainers:
  - name: jiramot
    email: jiramot@gmail.com
name: openapi
version: 0.1.4

dependencies:
  - name: kong
    repository: "https://charts.konghq.com"
    condition: kong.enabled
    version: 2.3.0
    alias: kong

  - name: redis
    repository: "https://charts.bitnami.com/bitnami"
    condition: redis.enabled
    version: 15.3.2
    alias: redis
